=head1 TestML Standard Library

A Standard Library for for TestML

=head1 Status

Working Draft - 17 May, 2009

This document is the TestML Standard Library Specification. Version
1.0.0 Pre-release.

This is not the final 1.0.0 release.

This document describes the standard library that every TestML 1.0
implementation must provide.

=head1 Overview

A TestML implementation requires a standard library that contaains the
I<transform functions>, 

=cut

